Airbnb/GreekTravel /src/java/model/BookingModel.java
package model;

//import static entities.User_.nickname;
import java.util.Date;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;

public class BookingModel {

    private Integer id;
    private Date date_from;
    private Date date_to;
    private Integer owner_rating;
    private Integer room_rating;
    private UserModel visitor;

    public UserModel getVisitor() {
        return visitor;
    }

    public void setVisitor(UserModel visitor) {
        this.visitor = visitor;
    }

    public Integer getId() {
        return id;
    }

    @XmlAttribute
    public void setId(Integer id) {
        this.id = id;
    }

    public Date getDateFrom() {
        return date_from;
    }

    @XmlElement
    public void setDateFrom(Date date_from) {
        this.date_from = date_from;
    }

    public Date getDateTo() {
        return date_to;
    }

    @XmlElement
    public void setDateTo(Date date_to) {
        this.date_to = date_to;
    }

    public Integer getOwnerRating() {
        return owner_rating;
    }

    @XmlElement
    public void setOwnerRating(Integer owner_rating) {
        this.owner_rating = owner_rating;
    }

    public Integer getRoomRating() {
        return room_rating;
    }

    @XmlElement
    public void setRoomRating(Integer room_rating) {
        this.room_rating = room_rating;
    }
}

Airbnb/GreekTravel /src/java/controllers/rooms/BookingController.java
package controllers.rooms;

import entities.User;
import java.util.Map;
import javax.servlet.http.HttpSession;
public class BookingController extends controllers.Controller{
    
    private final String target_error ="/WEB-INF/error/endoftheworld.jsp";
    private final String target_success ="/WEB-INF/fragments/Booking.jsp";
    
    private String roomId = null;
    private String ownerId = null;
    private User sessionuser = null;
    

    @Override
    protected boolean validate_input(Map<String, String[]> map) {
        return true;
    }

    @Override
    protected boolean validate_logic() {
        return true;
    }

    @Override
    protected boolean try_execute() {
    
        try {
            ownerId = map.get("ownerId")[0];
            roomId = map.get("roomId")[0];
            
            HttpSession session = request.getSession();
            sessionuser = (User) session.getAttribute("sessionuser");
            return true;
        } catch (Exception e) {

            return false;
        }
    }

    @Override
    protected void on_success() {
        request.setAttribute("roomId", roomId);
        request.setAttribute("ownerId", ownerId);
        request.setAttribute("sessionuser", sessionuser);
        redirect(target_success);
    }

    @Override
    protected void on_error() {
        redirect(target_error);
    }
}

Airbnb/GreekTravel /src/java/controllers/search/AdvancedSearchController.java
package controllers.search;

import dao.BookingDAO;
import dao.BookingDAOImpl;
import dao.RoomDAOImpl;
import dao.UserDAOImpl;
import entities.Role;
import entities.Room;
import entities.RoomType;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import validation.AddressValidator;
import validation.CountryNameValidator;
import validation.DateValidator;
import validation.DoublePositiveNegativeValidator;
import validation.DoublePositiveUperToZero;
import validation.PositiveIntegerValidator;
import validation.StringValidator;
import validation.TrueFalseValidator;
import validation.TypeValidator;

public class AdvancedSearchController extends controllers.Controller {

    private RoomDAOImpl dao = new RoomDAOImpl();
    private BookingDAO bd = new BookingDAOImpl();
 
    private final String target = "/WEB-INF/searchAdvancedResult.jsp";
    private final String target_error = "/WEB-INF/searchAdvancedResult.jsp";

    List<Room> list = null;
    List<Role> role = null;

    private Map< Room, Integer[]> SearchListFeatures = new HashMap<>();

    int currentPage;
    int recordsPerPage = 10;
    int noOfRecords;
    int numberOfPages;

    @Override
    protected boolean validate_input(Map<String, String[]> map) {

        DoublePositiveNegativeValidator doublev = new DoublePositiveNegativeValidator(errorMap, correctMap);
        DoublePositiveUperToZero dpv = new  DoublePositiveUperToZero(errorMap, correctMap);
        StringValidator sv = new StringValidator(errorMap, correctMap);
        CountryNameValidator cnv = new CountryNameValidator(errorMap, correctMap);
        PositiveIntegerValidator piv = new PositiveIntegerValidator(errorMap, correctMap);
        DateValidator dv = new DateValidator(errorMap, correctMap);
        AddressValidator av = new AddressValidator(errorMap, correctMap);
        TrueFalseValidator tfv = new TrueFalseValidator(errorMap, correctMap);
        TypeValidator tv = new TypeValidator(errorMap, correctMap);

        String smokingValue = map.get("smoking")[0];
        String petsValue = map.get("pets")[0];
        String eventsValue = map.get("events")[0];
        String wifiValue = map.get("wifi")[0];
        String refridgeratorValue = map.get("refridgerator")[0];
        String parkingValue = map.get("parking")[0];
        String kitchenValue = map.get("kitchen")[0];
        String elevatorValue = map.get("elevator")[0];
        String airconditionValue = map.get("aircondition")[0];
        String heatingValue = map.get("heating")[0];
        String  tvValue = map.get("tv")[0];
        String livingRoomValue = map.get("livingRoom")[0];

        String typeValue = map.get("type")[0];
        String peopleNumValue = map.get("peopleNum")[0];
        String costPerDayValue = map.get("costPerDay")[0];
        String distrinctValue = map.get("distrinct")[0];
        String cityValue = map.get("city")[0];
        String countryValue = map.get("country")[0];
        String addressValue = map.get("address")[0];

        String areaValue = map.get("area")[0];
        String floorValue = map.get("floor")[0];
        String bedNumberValue = map.get("bedNumber")[0];
        String wcNumberValue = map.get("wcNumber")[0];
        String bedroomNumberValue = map.get("bedroomNumber")[0];
        String minimumDaysValue = map.get("minimumDays")[0];

        dv.validate(map, "dateFrom");
        dv.validate(map, "dateTo");

        if ((areaValue != null) && (areaValue.trim().length() >= 1)) {
            dpv.validate(map, "area");
        } else {
            correctMap.put("area", null);
        }

        if ((floorValue != null) && (floorValue.trim().length() >= 1)) {
            piv.validate(map, "floor");
        } else {
            correctMap.put("floor", null);
        }

        if ((minimumDaysValue != null) && (minimumDaysValue.trim().length() >= 1)) {
            piv.validate(map, "minimumDays");
        } else {
            correctMap.put("minimumDays", null);
        }

        if ((wcNumberValue != null) && (wcNumberValue.trim().length() >= 1)) {
            piv.validate(map, "wcNumber");
        } else {
            correctMap.put("wcNumber", null);
        }

        if ((bedNumberValue != null) && (bedNumberValue.trim().length() >= 1)) {
            piv.validate(map, "bedNumber");
        } else {
            correctMap.put("bedNumber", null);
        }

        if ((bedroomNumberValue != null) && (bedroomNumberValue.trim().length() >= 1)) {
            piv.validate(map, "bedroomNumber");
        } else {
            correctMap.put("bedroomNumber", null);
        }

        if ((heatingValue != null) && (heatingValue.trim().length() > 1)) {
            tfv.validate(map, "heating");
        } else {
            correctMap.put("heating", null);
        }

        if ((tvValue != null) && (tvValue.trim().length() > 1)) {
            tfv.validate(map, "tv");
        } else {
            correctMap.put("tv", null);
        }

        if ((livingRoomValue != null) && (livingRoomValue.trim().length() > 1)) {
            tfv.validate(map, "livingRoom");
        } else {
            correctMap.put("livingRoom", null);
        }

        if ((kitchenValue != null) && (kitchenValue.trim().length() > 1)) {
            tfv.validate(map, "kitchen");
        } else {
            correctMap.put("kitchen", null);
        }

        if ((elevatorValue != null) && (elevatorValue.trim().length() > 1)) {
            tfv.validate(map, "elevator");
        } else {
            correctMap.put("elevator", null);
        }

        if ((airconditionValue != null) && (airconditionValue.trim().length() > 1)) {
            tfv.validate(map, "aircondition");
        } else {
            correctMap.put("aircondition", null);
        }

        if ((wifiValue != null) && (wifiValue.trim().length() > 1)) {
            tfv.validate(map, "wifi");
        } else {
            correctMap.put("wifi", null);
        }

        if ((refridgeratorValue != null) && (refridgeratorValue.trim().length() > 1)) {
            tfv.validate(map, "refridgerator");
        } else {
            correctMap.put("refridgerator", null);
        }

        if ((parkingValue != null) && (parkingValue.trim().length() > 1)) {
            tfv.validate(map, "parking");
        } else {
            correctMap.put("parking", null);
        }

        if ((smokingValue != null) && (smokingValue.trim().length() > 1)) {
            tfv.validate(map, "smoking");
        } else {
            correctMap.put("smoking", null);
        }

        if ((petsValue != null) && (petsValue.trim().length() > 1)) {
            tfv.validate(map, "pets");
        } else {
            correctMap.put("pets", null);
        }

        if ((eventsValue != null) && (eventsValue.trim().length() > 1)) {
            tfv.validate(map, "events");
        } else {
            correctMap.put("events", null);
        }

        if ((typeValue != null) && (typeValue.trim().length() > 1)) {
            tv.validate(map, "type");
        } else {
            correctMap.put("type", null);
        }

        if ((countryValue != null) && (countryValue.trim().length() > 1)) {
            cnv.validate(map, "country");
        } else {
            correctMap.put("country", null);
        }

        if ((cityValue != null) && (cityValue.trim().length() > 1)) {
            cnv.validate(map, "city");
        } else {
            correctMap.put("city", null);
        }

        if ((distrinctValue != null) && (distrinctValue.trim().length() > 1)) {
            cnv.validate(map, "distrinct");
        } else {
            correctMap.put("distrinct", null);
        }

        if ((peopleNumValue != null) && (peopleNumValue.trim().length() >= 1)) {
            piv.validate(map, "peopleNum");
        } else {
            correctMap.put("peopleNum", null);
        }

        if ((costPerDayValue != null) && (costPerDayValue.trim().length() >= 1)) {
            dpv.validate(map, "costPerDay");
        } else {
            correctMap.put("costPerDay", null);
        }

        if ((addressValue != null) && (addressValue.trim().length() > 1)) {
            av.validate(map, "address");
        } else {
            correctMap.put("address", null);
        }
        
                
        if (map.get("currentPage") == null) {
            currentPage = 1;
        } else {
            PositiveIntegerValidator pv = new PositiveIntegerValidator(errorMap, correctMap);
            pv.validate(map, "currentPage");
            String stringCurrentPage = correctMap.get("currentPage");
            currentPage = Integer.parseInt(stringCurrentPage);
        }


        return errorMap.isEmpty();
    }

    @Override
    protected boolean validate_logic() {
        return true;
    }

    @Override
    protected boolean try_execute() {

        try {

            int minDays = 0;
            int wcNum = 0;
            int bedNum = 0;
            int bedroomNum = 0;
            Integer flor = 0;
            int pNumber = 0;
            double costPday = 0;
            double ar = 0;

            Date startDate = null;
            Date endDate = null;

            Boolean wf = null;
            Boolean rfr = null;
            Boolean prk = null;
            Boolean ktc = null;
            Boolean elv = null;
            Boolean ac = null;
            Boolean heat = null;
            Boolean tivi = null;
            Boolean li_room = null;
            Boolean smok = null;
            Boolean pet = null;
            Boolean event = null;

            if (correctMap.get("area") != null && !correctMap.get("area").isEmpty()) {
                ar = Double.parseDouble(correctMap.get("area"));
            }
            if (correctMap.get("minimumDays") != null && !correctMap.get("minimumDays").isEmpty()) {
                minDays = Integer.parseInt(correctMap.get("minimumDays"));

Airbnb/GreekTravel /src/java/controllers/search/RecommendationsController.java
package controllers.search;

import dao.BookingDAO;
import dao.BookingDAOImpl;
import dao.RoomDAOImpl;
import entities.Room;

import entities.User;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.servlet.http.HttpSession;


public class RecommendationsController extends controllers.Controller {

    private final String target = "/WEB-INF/index.jsp";
    private final String target_error = "/WEB-INF/index.jsp";

    private RoomDAOImpl dao = new RoomDAOImpl();
    private BookingDAO bd = new BookingDAOImpl();
    private Map< Room, Integer[]> SearchListFeatures = new HashMap<>();

    List<Room> list = null;

    @Override
    protected boolean validate_input(Map<String, String[]> map) {
        return true;
    }

    @Override
    protected boolean validate_logic() {
        return true;
    }

    @Override
    protected boolean try_execute() {
    
        try {
       
            HttpSession session = request.getSession();

            User sessionuser = null;
            if (session != null) {
                sessionuser = (User) session.getAttribute("sessionuser");
            }

            if (sessionuser == null) {
                System.out.println("mpeni sti periptosi random");
                list = dao.getRandomRooms();
            } else {
                   System.out.println("mpeni stis periptosis pou to session den einia 0");
                Integer id = sessionuser.getId();

                list = dao.findRecommendationsByUserId(id);
            }

            for (Room r : list) {
                Integer[] avgAndReviews = new Integer[2];

                avgAndReviews[0] = bd.findAvgRating(r.getId());
                avgAndReviews[1] = bd.findReviews(r.getId());

                SearchListFeatures.put(r, avgAndReviews);
            }

            return true;
        } catch (Exception e) {
            errorMap.addError("exception", e.getMessage());
            return false;
        }
    }

    @Override
    protected void on_success() {
        request.setAttribute("SearchListFeatures", SearchListFeatures);
        redirect(target);
    }

    @Override
    protected void on_error() {
        redirect(target_error);
    }
}

Airbnb/GreekTravel /src/java/servlets/search/SearchServlet.java
package servlets.search;

import controllers.search.SearchController;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Map;
import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;


@WebServlet(name = "SearchServlet", urlPatterns = {"/user/search"})
public class SearchServlet extends HttpServlet {

    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        ServletContext servletContext = getServletContext();
        
        try (PrintWriter out = response.getWriter()) {
            SearchController controller = new SearchController();
            
            Map<String, String[]> parameterMap = request.getParameterMap();
            
            
            controller.execute(servletContext, parameterMap, request, response);
        }
    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}

Airbnb/GreekTravel /web/WEB-INF/fragments/Booking.jsp
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>

<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <jsp:include page="/WEB-INF/fragments/common/head.jsp"/>
    </head>

    <body>
        <div id="wrap">            
            <jsp:include page="/WEB-INF/fragments/common/topbar.jsp"/>

            <jsp:include page="/WEB-INF/fragments/common/header.jsp"/>

            <div id="content">
                <div id="home_main">                    
                    <jsp:include page="/WEB-INF/fragments/book_details.jsp"/>                                        
                </div>

                <!--<div id="sidebar">-->
                <%--<jsp:include page="/WEB-INF/fragments/common/sidebar.jsp"/>--%>                                              
                <!--</div>--> 

            </div> 
            <jsp:include page="/WEB-INF/fragments/common/footer.jsp"/>
        </div>
        <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.5.1/moment.min.js"></script>
        <script src="${pageContext.request.contextPath}/js/pikaday.js" type="text/javascript"></script>
        <script src="${pageContext.request.contextPath}/js/date.js" type = "text/javascript"></script>
    </body>
</html>

Airbnb/GreekTravel /web/WEB-INF/fragments/basic_search.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>


<div id="search">
    <div class="tab">
        <h2>Search Property To Rent</h2>
    </div>
    <div class="container">
        <form id="form1" action="${pageContext.request.contextPath}/user/search" method="POST">
            <table class="search_form" style="width:100%; border:none;">

                <tr>
                    <td class="label">Date From</td>
                    <td>
                        <input placeholder ="Click to select date from"  type="text" name="dateFrom" id="start" class="text" value="${dateFrom}" />
                        <c:forEach items="${errorMap.dateFrom}" var="obj">
                            <p class="fielderror">${obj}</p>
                        </c:forEach>
                    </td>
                    <td class="label">Date To</td>
                    <td>
                        <input placeholder ="Click to select date to"  type="text" name="dateTo" id="end" class="text" value="${dateTo}"/>
                        <c:forEach items="${errorMap.dateTo}" var="obj">
                            <p class="fielderror">${obj}</p>
                        </c:forEach>
                    </td>
                </tr>
                
                <!--<tr>-->
                    <!--<td class="label">Address</td>-->
                    <!--<td colspan="3">-->
                        <!--<label>-->
                            <input  placeholder ="Athens Address 1" type="hidden" name="address" id="address" class="text longfield" value="${address}" />
                            <!--<br>-->
                        <!--</label>-->
                        <c:forEach items="${errorMap.address}" var="obj">
                            <p class="fielderror">${obj}</p>
                        </c:forEach>
                    <!--</td>-->
                <!--</tr>-->
                <tr>
                    <td class="label">Country</td>
                    <td>
                        <input placeholder ="Greece"  type="text" name="country" id="country" class="text" value="${country}"  />
                        <c:forEach items="${errorMap.country}" var="obj">
                            <p class="fielderror">${obj}</p>
                        </c:forEach>
                    </td>
                    <td class="label">City</td>
                    <td>
                        <input placeholder ="Athens"  type="text" name="city" id="city" class="text" value="${city}"/>
                        <c:forEach items="${errorMap.city}" var="obj">
                            <p class="fielderror">${obj}</p>
                        </c:forEach>
                    </td>
                </tr>
                <tr>
                    <td class="label">District</td>
                    <td>
                        <input placeholder ="Hlisia "  type="text" name="distrinct" id="distrinct" class="text" value="${distrinct}"/>
                        <c:forEach items="${errorMap.distrinct}" var="obj">
                            <p class="fielderror">${obj}</p>
                        </c:forEach>
                    </td>
                    <td class="label">Type</td>
                    <td width="50%">
                        <label>
                            <select name="type" class="select_field"  >
                                <option value="" >Not interested</option>
                                <option value="private room" ${type  == "private room" ? 'selected' : ''}>Private room</option>
                                <option value="shared room" ${type  == "shared room" ? 'selected' : ''}>Shared room</option>
                                <option value="house" ${type  == "house" ? 'selected' : ''}>House</option>
                                <option value="villa" ${type  == "villa" ? 'selected' : ''}>Villa</option>
                            </select>
                        </label>
                    </td>
                </tr>


                <tr>
                    <td class="label">Cost Per Day</td>
                    <td>
                        <input placeholder ="50" type="text" name="costPerDay" id="costPerDay" class="text" value="${costPerDay}" />
                        <c:forEach items="${errorMap.costPerDay}" var="obj">
                            <p class="fielderror">${obj}</p>
                        </c:forEach>
                    </td>
                    <td class="label">People Number</td>
                    <td>
                        <input  placeholder ="2" type="text" name="peopleNum" id="peopleNum" class="text" value="${peopleNum}"/>
                        <c:forEach items="${errorMap.peopleNum}" var="obj">
                            <p class="fielderror">${obj}</p>
                        </c:forEach>
                    </td>
                </tr>

                <tr>
                    <td class="label">&nbsp;</td>
                    <td>&nbsp;</td>
                    <td colspan="2" class="label">
                        <label>
                            <br>
                            <input type="image" src="${pageContext.request.contextPath}/images/searchbtn.gif" alt="search" name="button2" id="button2" value="Submit" />
                        </label>
                    </td>
                </tr>
            </table>
        </form>
    </div>
</div>

Airbnb/GreekTravel /web/WEB-INF/fragments/paginations.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<div id="paginations">
    <ul>
        <li><a href="#">&laquo;</a></li>
        <li class="current"><a href="#">1</a></li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li><a href="#">5</a></li>
        <li><a href="#">6</a></li>
        <li><a href="#">7</a></li>
        <li><a href="#">8</a></li>
        <li><a href="#">0</a></li>
        <li><a href="#">10</a></li>
        <li><a href="#">&raquo;</a></li>
    </ul>
    <div class="clear">&nbsp;</div>
</div>

Airbnb/GreekTravel /web/WEB-INF/fragments/rentings.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<jsp:useBean id="now" class="java.util.Date"/>

<div id="recommendations">
    <div class="tab">
        <h2>My Bookings</h2>
    </div>
    <div class="container">
        <div class="listing">
            <ul>
                <form action="${pageContext.request.contextPath}/myrentings/rating" method="POST">
                    <c:forEach var="rentings" items="${list}">
                        <li style="display: block; height: 200px; width: 95%;">
                            <div class="listinfo">
                                <img src="${rentings.roomId.photoList[0].photographUrl}" alt="Photo" class="listingimage" style=" height: 150px;"/><!--width: 100px;-->
                                <!--<h3>Room id $ {recommendations.key.id};-->
                                <h3>
                                    ${rentings.roomId.locationList[0].city}, ${rentings.roomId.countryId.name} (${rentings.roomId.roomTypeList[0].type})
                                </h3>
                                </br>
                                <span class="price">Date From: ${rentings.dateFrom}</span> 
                                <span class="price">Date To: ${rentings.dateTo}</span>  
                                <c:if test="${not empty rentings.roomRating && not empty rentings.ownerRating }">
                                    </br>

                                    <div class="rating">

                                        <span class="review-no">
                                            Room Rating:
                                            <c:forEach begin="1" end="${rentings.roomRating}">
                                                <span class="fa fa-star checked" style="color: #e6b800; font-size: 15px;"></span>
                                            </c:forEach>
                                        </span>
                                    </div>

                                    </br>
                                    <div class="rating">
                                        <span class="review-no">
                                            Owner Rating:
                                            <c:forEach begin="1" end="${rentings.ownerRating}">
                                                <span class="fa fa-star checked" style="color: #e6b800; font-size: 15px;"></span>
                                            </c:forEach>
                                        </span>
                                    </div>
                                </c:if>
<!--                                <form action="$ {pageContext.request.contextPath}/room/details" method="POST">-->
<!--                                    <div>     
                                        <button name="Room_id" type="submit" value="$ {rentings.roomId}">More Details</button>
                                    </div>-->
                                <!--</form>-->
                            </div>
                            <c:if test="${empty rentings.roomRating && empty rentings.ownerRating }">
                                <fmt:formatDate value="${now}" pattern="yyyy/MM/dd" var="currentDate"/>
                                <fmt:formatDate value="${rentings.dateTo}" pattern="yyyy/MM/dd" var="dateToCommper" />
                                <!-- >= -->
                                <%--<c:if test="${dateToCommper le currentDate}">--%> 
                                <!-- > -->
                                <c:if test="${dateToCommper lt currentDate}">
                                    <div>
                                        <button name="rentingId" type="submit" value="${rentings.id}" class="ViewDetails">Rate Room</button>
                                    </div>
                                </c:if>
                            </c:if>
                        </li>
                    </c:forEach>
                </form>
            </ul>
        </div>
    </div>
</div>




<div id="paginations">
    <ul> 
        <li>
            <c:if test="${currentPage != 1}">    
                <a href="${pageContext.request.contextPath}/visitor/rentings?currentPage=${1}">&laquo;</a>
            </c:if>
        </li>

        <li>
            <c:if test="${currentPage != 1}">    
                <a href="${pageContext.request.contextPath}/visitor/rentings?currentPage=${currentPage - 1}">&lt;</a>
            </c:if>
        </li>

        <c:forEach begin="1" end="${numberOfPages}" var="i">
            <c:choose>
                <c:when test="currentPage eq i">
                    <li>
                        <a href="${pageContext.request.contextPath}/visitor/rentings?currentPage=${i}"></a>
                    </li>
                </c:when>
                <c:otherwise>
                    <li>
                        <a href="${pageContext.request.contextPath}/visitor/rentings?currentPage=${i}">${i}</a>
                    </li>
                </c:otherwise>
            </c:choose>

        </c:forEach>
        <li>
            <c:if test="${currentPage lt numberOfPages}">
                <a href="${pageContext.request.contextPath}/visitor/rentings?currentPage=${currentPage + 1}">&gt;</a>
            </c:if>
        </li>
        <li>
            <c:if test="${currentPage lt numberOfPages}">
                <a href="${pageContext.request.contextPath}/visitor/rentings?currentPage=${numberOfPages}">&raquo;</a>
            </c:if>
        </li>
    </ul>
    <div class="clear">&nbsp;</div>
</div>

Airbnb/GreekTravel /web/WEB-INF/fragments/topcategorieslink.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<div id="topcategorieslink" class="clear">
    <h2>Categories</h2>
    <ul>
        <li><a href="#">Villas</a> </li>
        <li><a href="#">Houses</a> </li>
        <li><a href="#">Apartments</a> </li>
        <li><a href="#">Bangalows</a> </li>
       
    </ul>
</div>
<div class="clear">&nbsp;</div>